# Generated by Django 2.0.3 on 2018-03-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pizza_id',
            new_name='pizza',
        ),
    ]
